class DetailOption {
  const DetailOption(this.label,{this.next,this.result});
  final String label;
  final String? next;
  final String? result;
}
class DetailStep {
  const DetailStep({required this.id,required this.title,required this.help,required this.options});
  final String id,title,help; final List<DetailOption> options;
}
class DetailKey {
  const DetailKey({required this.id,required this.title,required this.start,required this.steps,required this.sourceNote});
  final String id,title,start,sourceNote; final Map<String,DetailStep> steps;
}
// Only distinctions already encoded from the supplied source material belong here.
// These keys deliberately stop at group/genus level when no complete species key is present.
const russulaceaeDetailKey=DetailKey(id:'russulaceae',title:'Russulaceae-detailsleutel',start:'milk',sourceNote:'Bronondersteunde splitsing op melk/sap; de aangeleverde bron bevat nog geen volledige soortensleutel.',steps:{'milk':DetailStep(id:'milk',title:'Komt er melksap vrij bij beschadiging?',help:'Beschadig voorzichtig een plaatje of het vlees en observeer of er melk/sap verschijnt.',options:[DetailOption('Melksap aanwezig',result:'Lactarius'),DetailOption('Geen melksap',result:'Russula'),DetailOption('Niet beoordeeld',result:'Russula/Lactarius')])});
const shellDetailKey=DetailKey(id:'shell',title:'Schelpzwammen — broncontrole',start:'stem',sourceNote:'De bron ondersteunt Schelpzwammen vooral via een vrijwel afwezige of zijdelings aangehechte steel. De onderzijde kan lamellen, rimpels of vrijwel geen structuur hebben en is dus geen harde groepsfilter.',steps:{'stem':DetailStep(id:'stem',title:'Hoe is de steel aangehecht?',help:'Controleer het bronkenmerk dat het huidige hoofdwiel nog niet rechtstreeks vraagt.',options:[DetailOption('Steel vrijwel afwezig',result:'Schelpzwammen — kandidaatgroep'),DetailOption('Steel zijdelings aangehecht',result:'Schelpzwammen — kandidaatgroep'),DetailOption('Duidelijke centrale steel',result:'Schelpzwammen minder ondersteund; vergelijk andere groepen'),DetailOption('Onzeker',result:'Schelpzwammen blijven mogelijk; steelstand niet beoordeeld')])});
const pleurotusDetailKey=DetailKey(id:'pleurotus',title:'Oesterzwammen — broncontrole',start:'confirm',sourceNote:'De 2016-bron ondersteunt Pleurotus als eigen geslachtsgroep; deze controle stopt vóór soortniveau.',steps:{'confirm':DetailStep(id:'confirm',title:'Controleer het groepsprofiel',help:'Controleer witachtige aflopende lamellen, een meestal korte zijdelingse steel, wit tot roomkleurige sporee en het ontbreken van velum.',options:[DetailOption('Profiel bevestigd',result:'Pleurotus (Oesterzwammen)'),DetailOption('Niet zeker',result:'Pleurotus-kandidaat; opnieuw beoordelen')])});
const pluteusDetailKey=DetailKey(id:'pluteus',title:'Hertenzwammen-detailsleutel',start:'confirm',sourceNote:'Deze controle gebruikt de diagnostische combinatie van roze sporen, vrije plaatjes en geen zichtbaar velum. De bron noemt saprotrofie en vaak groei op hout als ecologie, niet als verplichte uitsluitingsvoorwaarde.',steps:{'confirm':DetailStep(id:'confirm',title:'Controleer de combinatie',help:'Bevestig vrije plaatjes, roze sporen en geen zichtbaar velum. Groei op hout ondersteunt de kandidaat, maar de bron zegt ‘vaak op hout’ en maakt dit dus niet verplicht. De huidige bronset ondersteunt daarna alleen het geslacht/groepniveau.',options:[DetailOption('Combinatie bevestigd',result:'Pluteus (Hertenzwammen)'),DetailOption('Niet zeker',result:'Pluteus-kandidaat; verdere detailsleutel nodig')])});
const galerinaDetailKey=DetailKey(id:'galerina',title:'Mosklokjes-detailsleutel',start:'substrate',sourceNote:'De bron ondersteunt bruine/roestkleurige sporen. Mos is een vaak genoemde groeiplaats en dood hout komt soms voor; deze ecologie is ondersteunend en niet exclusief.',steps:{'substrate':DetailStep(id:'substrate',title:'Waar groeit het exemplaar?',help:'Leg het waargenomen substraat vast als ondersteunende ecologie. Een andere groeiplaats sluit Galerina op basis van deze bron niet uit.',options:[DetailOption('Gras / mos',result:'Galerina (Mosklokjes) — kandidaatgroep'),DetailOption('Dood hout',result:'Galerina (Mosklokjes) — kandidaatgroep'),DetailOption('Andere groeiplaats',result:'Galerina-kandidaat; ecologie niet doorslaggevend'),DetailOption('Onzeker',result:'Galerina-kandidaat; ecologie niet doorslaggevend')])});
const hebelomaDetailKey=DetailKey(id:'hebeloma',title:'Vaalhoeden-detailsleutel',start:'confirm',sourceNote:'Deze controle gebruikt bruine/roestkleurige sporen en geen zichtbaar velum. De bron vermeldt ectomycorrhiza, maar dat is niet hetzelfde als de app-categorie ‘bodem / strooisel’ en wordt daarom niet als harde substraatvoorwaarde gebruikt.',steps:{'confirm':DetailStep(id:'confirm',title:'Controleer het bronprofiel',help:'Bevestig sporenkleur en het ontbreken van zichtbaar velum. Noteer ecologie afzonderlijk; voor soortniveau ontbreken nog gecodeerde detailcriteria.',options:[DetailOption('Profiel bevestigd',result:'Hebeloma (Vaalhoeden)'),DetailOption('Niet zeker',result:'Hebeloma-kandidaat; verdere detailsleutel nodig')])});
const agrocybeDetailKey=DetailKey(id:'agrocybe',title:'Leemhoeden-detailsleutel',start:'confirm',sourceNote:'De bron ondersteunt een bleekbruine sporee en vermeldt dat Agrocybe meestal op de bodem groeit. ‘Meestal’ wordt hier niet als verplichte uitsluitingsvoorwaarde gebruikt; de bron ondersteunt nog geen betrouwbare soortnaam.',steps:{'confirm':DetailStep(id:'confirm',title:'Controleer sporenkleur en ecologie',help:'Controleer de sporenkleur. Bodemgroei ondersteunt de kandidaat, maar is volgens de bron niet verplicht. Gebruik deze stap niet als soortdeterminatie.',options:[DetailOption('Combinatie bevestigd',result:'Agrocybe (Leemhoeden)'),DetailOption('Niet zeker',result:'Agrocybe-kandidaat; verdere detailsleutel nodig')])});

const parasolDetailKey=DetailKey(id:'parasol',title:'Parasolzwammen — broncontrole',start:'confirm',sourceNote:'De bron ondersteunt de parasolzwammen als groep; de getoonde kenmerken zijn niet voldoende voor een soortnaam.',steps:{'confirm':DetailStep(id:'confirm',title:'Controleer het groepsprofiel',help:'Vrije lamellen, wit/crème tot bleekroze sporee, velum en vaak een ring, saprotroof op de bodem.',options:[DetailOption('Profiel bevestigd',result:'Lepiota en verwanten — kandidaatgroep'),DetailOption('Niet zeker',result:'Parasolzwam-kandidaat; opnieuw beoordelen')])});
const laccariaDetailKey=DetailKey(id:'laccaria',title:'Fopzwammen — broncontrole',start:'confirm',sourceNote:'De bron ondersteunt Laccaria als geslacht; voor soortniveau ontbreekt hier een volledige detailsleutel.',steps:{'confirm':DetailStep(id:'confirm',title:'Controleer het groepsprofiel',help:'Klein, zonder velum, dikke wijd uiteenstaande lamellen, witte sporen en sterk hygrofane hoed.',options:[DetailOption('Profiel bevestigd',result:'Laccaria (Fopzwammen)'),DetailOption('Niet zeker',result:'Laccaria-kandidaat; opnieuw beoordelen')])});

const waxcapDetailKey=DetailKey(id:'waxcaps',title:'Wasplaten / Slijmkoppen — broncontrole',start:'confirm',sourceNote:'De bron ondersteunt hier een groepsprofiel, geen volledige soortensleutel.',steps:{'confirm':DetailStep(id:'confirm',title:'Controleer het groepsprofiel',help:'Let op witte sporee, vettige en wijd uiteenstaande lamellen en het hoedoppervlak.',options:[DetailOption('Profiel bevestigd',result:'Hygrocybe/Hygrophorus — kandidaatgroep'),DetailOption('Niet zeker',result:'Wasplaat/Slijmkop-kandidaat; opnieuw beoordelen')])});
const funnelDetailKey=DetailKey(id:'funnel',title:'Trechtertjes — broncontrole',start:'confirm',sourceNote:'De bron ondersteunt Omphalina/Rickenella als groep, maar geen volledige soortensleutel.',steps:{'confirm':DetailStep(id:'confirm',title:'Controleer het groepsprofiel',help:'Klein, trechtervormig, wijd uiteenstaande aflopende lamellen, geen velum en wit/roomkleurige sporee.',options:[DetailOption('Profiel bevestigd',result:'Omphalina/Rickenella — kandidaatgroep'),DetailOption('Niet zeker',result:'Trechtertje-kandidaat; opnieuw beoordelen')])});
const toughshankDetailKey=DetailKey(id:'toughshanks',title:'Taailingen — broncontrole',start:'confirm',sourceNote:'De bron ondersteunt deze groep op macroscopisch niveau, maar niet een volledige soortensleutel.',steps:{'confirm':DetailStep(id:'confirm',title:'Controleer het groepsprofiel',help:'Klein tot middelgroot, zonder velum, vaak taai en uitdrogingsbestendig, met wit tot roomkleurige sporee.',options:[DetailOption('Profiel bevestigd',result:'Taailingen en verwanten — kandidaatgroep'),DetailOption('Niet zeker',result:'Taailing-kandidaat; opnieuw beoordelen')])});
const pholiotaDetailKey=DetailKey(id:'pholiota',title:'Bundelzwammen — broncontrole',start:'confirm',sourceNote:'De bron ondersteunt Pholiota/Kuehneromyces als groep; soortniveau vraagt een echte detailsleutel.',steps:{'confirm':DetailStep(id:'confirm',title:'Controleer het groepsprofiel',help:'Bruine sporee, aangehechte lamellen, vaak velum/ringresten en vaak groei op hout.',options:[DetailOption('Profiel bevestigd',result:'Pholiota/Kuehneromyces — kandidaatgroep'),DetailOption('Niet zeker',result:'Bundelzwam-kandidaat; opnieuw beoordelen')])});
const strophariaDetailKey=DetailKey(id:'stropharia',title:'Kaalkopjes / Stropharia — broncontrole',start:'confirm',sourceNote:'De bron ondersteunt deze groep via de purpertint van sporee/rijpe lamellen en saprotrofe leefwijze.',steps:{'confirm':DetailStep(id:'confirm',title:'Controleer het groepsprofiel',help:'Controleer vooral de purpertint in de sporee; velum kan aanwezig of afwezig zijn.',options:[DetailOption('Profiel bevestigd',result:'Stropharia/Hypholoma/Psilocybe/Deconica — kandidaatgroep'),DetailOption('Niet zeker',result:'Kaalkopje/Stropharia-kandidaat; opnieuw beoordelen')])});

const paxillusDetailKey=DetailKey(id:'paxillus',title:'Krulzomen — broncontrole',start:'confirm',sourceNote:'De aangeleverde bron ondersteunt Paxillus/Tapinella als groep, niet een volledige soortensleutel.',steps:{'confirm':DetailStep(id:'confirm',title:'Controleer het groepsprofiel',help:'Bruine sporee, sterk aflopende vaak aderig vertakte plaatjes en vlees dat bij kwetsen donkerbruin verkleurt.',options:[DetailOption('Profiel bevestigd',result:'Paxillus/Tapinella — kandidaatgroep'),DetailOption('Niet zeker',result:'Krulzoom-kandidaat; opnieuw beoordelen')])});
const cantharellusDetailKey=DetailKey(id:'cantharellus',title:'Cantharellen — broncontrole',start:'confirm',sourceNote:'De aangeleverde bron ondersteunt Cantharellus als geslacht; soortniveau is hiermee niet betrouwbaar vastgelegd.',steps:{'confirm':DetailStep(id:'confirm',title:'Controleer het groepsprofiel',help:'Hoed met centrale steel en lamelachtige of aderachtige lijsten; sporee crème-geelachtig.',options:[DetailOption('Profiel bevestigd',result:'Cantharellus (Cantharellen)'),DetailOption('Niet zeker',result:'Cantharellus-kandidaat; opnieuw beoordelen')])});

DetailKey? detailKeyFor({String? genusHint,Iterable<String> candidateNames=const []}){
  if(genusHint=='Lactarius'||genusHint=='Russula') return russulaceaeDetailKey;
  if(candidateNames.length!=1) return null;
  final name=candidateNames.first;
  if(name.contains('Schelpzwammen')) return shellDetailKey;
  if(name.contains('Parasolzwammen')) return parasolDetailKey;
  if(name.contains('Laccaria')) return laccariaDetailKey;
  if(name.contains('Pleurotus')) return pleurotusDetailKey;
  if(name.contains('Pluteus')) return pluteusDetailKey;
  if(name.contains('Galerina')) return galerinaDetailKey;
  if(name.contains('Hebeloma')) return hebelomaDetailKey;
  if(name.contains('Agrocybe')) return agrocybeDetailKey;
  if(name.contains('Wasplaten')) return waxcapDetailKey;
  if(name.contains('Omphalina')) return funnelDetailKey;
  if(name.contains('Taailingen')) return toughshankDetailKey;
  if(name.contains('Pholiota')) return pholiotaDetailKey;
  if(name.contains('Stropharia')) return strophariaDetailKey;
  if(name.contains('Paxillus')) return paxillusDetailKey;
  if(name.contains('Cantharellus')) return cantharellusDetailKey;
  return null;
}
