import 'package:flutter/material.dart';

import '../../../l10n/app_localizations.dart';
import '../../data/models.dart';
import '../../data/repositories.dart';
import '../../data/resilient_identification_repository.dart';
import '../../widgets/safety_notice.dart';
import '../species/species_screen.dart';
import 'measurement_input.dart';
import 'trait_visual.dart';

class IdentifyScreen extends StatefulWidget {
  const IdentifyScreen({super.key,required this.locale,this.repository,this.fieldDataRepository});
  final Locale locale; final IdentificationRepository? repository; final FieldDataRepository? fieldDataRepository;
  @override State<IdentifyScreen> createState()=>_IdentifyScreenState();
}
class _IdentifyScreenState extends State<IdentifyScreen>{
  late final IdentificationRepository _repo; late final FieldDataRepository _fieldRepo;
  final _capController=TextEditingController(),_stemController=TextEditingController(),_stemDiameterController=TextEditingController();
  late Future<List<TraitChoice>> _choices; late Future<List<SeasonRegionOption>> _regions;
  final Map<int,int> _selected={}; List<IdentificationCandidate>? _results; String? _seasonRegion; int? _observationMonth;
  MeasurementInputStatus? _capError,_stemError,_stemDiameterError; bool _seasonMonthMissing=false;
  @override void initState(){super.initState();_repo=widget.repository??ResilientIdentificationRepository();_fieldRepo=widget.fieldDataRepository??FieldDataRepository();_choices=_repo.choices(widget.locale.languageCode);_regions=_fieldRepo.seasonRegions(widget.locale.languageCode);}
  @override void dispose(){_capController.dispose();_stemController.dispose();_stemDiameterController.dispose();super.dispose();}
  void _retryChoices()=>setState(()=>_choices=_repo.choices(widget.locale.languageCode));
  String? _measurementError(AppLocalizations l,MeasurementInputStatus? s)=>s==MeasurementInputStatus.invalidNumber?l.identifyInvalidNumber:s==MeasurementInputStatus.nonPositive?l.identifyNonPositive:null;
  Future<void> _identify() async {final cap=parseMeasurementInput(_capController.text),stem=parseMeasurementInput(_stemController.text),diam=parseMeasurementInput(_stemDiameterController.text);final missing=_seasonRegion!=null&&_observationMonth==null;setState((){_capError=cap.isValid?null:cap.status;_stemError=stem.isValid?null:stem.status;_stemDiameterError=diam.isValid?null:diam.status;_seasonMonthMissing=missing;});if(!cap.isValid||!stem.isValid||!diam.isValid||missing)return;final r=await _repo.identify(widget.locale.languageCode,_selected,observationMonth:_seasonRegion==null?null:_observationMonth,seasonRegionCode:_seasonRegion,capDiameterCm:cap.value,stemHeightCm:stem.value,stemDiameterCm:diam.value);if(mounted)setState(()=>_results=r);}
  String _monthName(AppLocalizations l,int m)=>[l.monthJan,l.monthFeb,l.monthMar,l.monthApr,l.monthMay,l.monthJun,l.monthJul,l.monthAug,l.monthSep,l.monthOct,l.monthNov,l.monthDec][m-1];
  Widget _traitCard(BuildContext context,AppLocalizations l,List<TraitChoice> items){final selected=_selected[items.first.traitId];return Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(items.first.traitLabel,style:Theme.of(context).textTheme.titleMedium)),Text('${items.length}',style:Theme.of(context).textTheme.labelMedium)]),const SizedBox(height:4),Text(l.identifyIntro,style:Theme.of(context).textTheme.bodySmall),const SizedBox(height:10),GridView.builder(key:ValueKey('trait-grid-${items.first.traitId}'),shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:items.length,gridDelegate:const SliverGridDelegateWithMaxCrossAxisExtent(maxCrossAxisExtent:156,mainAxisExtent:140,crossAxisSpacing:8,mainAxisSpacing:8),itemBuilder:(context,index){final choice=items[index],isSelected=selected==choice.optionId;return InkWell(borderRadius:BorderRadius.circular(12),onTap:()=>setState(()=>_selected[choice.traitId]=choice.optionId),child:AnimatedContainer(duration:const Duration(milliseconds:150),padding:const EdgeInsets.all(6),decoration:BoxDecoration(borderRadius:BorderRadius.circular(12),border:Border.all(color:isSelected?Theme.of(context).colorScheme.primary:Theme.of(context).colorScheme.outlineVariant,width:isSelected?2:1),color:isSelected?Theme.of(context).colorScheme.primaryContainer.withValues(alpha:.35):null),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[TraitVisual(traitCode:choice.traitCode,optionId:choice.optionId,optionLabel:choice.optionLabel,size:64),const SizedBox(height:5),Flexible(child:Text(choice.optionLabel,textAlign:TextAlign.center,maxLines:3,overflow:TextOverflow.ellipsis,style:Theme.of(context).textTheme.labelMedium)),if(isSelected)Icon(Icons.check_circle,size:18,color:Theme.of(context).colorScheme.primary)])));}),if(selected!=null)Align(alignment:Alignment.centerRight,child:TextButton.icon(onPressed:()=>setState(()=>_selected.remove(items.first.traitId)),icon:const Icon(Icons.clear),label:Text(l.identifyClear)))])));}
  Widget _fieldDataCard(AppLocalizations l)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(l.identifyFieldData,style:Theme.of(context).textTheme.titleMedium),const SizedBox(height:8),TextField(controller:_capController,keyboardType:const TextInputType.numberWithOptions(decimal:true),onChanged:(_){if(_capError!=null)setState(()=>_capError=null);},decoration:InputDecoration(labelText:l.identifyCapDiameter,errorText:_measurementError(l,_capError))),const SizedBox(height:8),TextField(controller:_stemController,keyboardType:const TextInputType.numberWithOptions(decimal:true),onChanged:(_){if(_stemError!=null)setState(()=>_stemError=null);},decoration:InputDecoration(labelText:l.identifyStemHeight,errorText:_measurementError(l,_stemError))),const SizedBox(height:8),TextField(controller:_stemDiameterController,keyboardType:const TextInputType.numberWithOptions(decimal:true),onChanged:(_){if(_stemDiameterError!=null)setState(()=>_stemDiameterError=null);},decoration:InputDecoration(labelText:l.identifyStemDiameter,errorText:_measurementError(l,_stemDiameterError))),const SizedBox(height:12),FutureBuilder<List<SeasonRegionOption>>(future:_regions,builder:(context,s){final regions=s.data??const<SeasonRegionOption>[];final selected=regions.where((r)=>r.code==_seasonRegion).firstOrNull;return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[DropdownButtonFormField<String?>(key:ValueKey(_seasonRegion),initialValue:_seasonRegion,decoration:InputDecoration(labelText:l.identifySeasonReference),items:[DropdownMenuItem<String?>(value:null,child:Text(l.identifyDoNotUse)),...regions.map((r)=>DropdownMenuItem<String?>(value:r.code,child:Text(r.label)))],onChanged:s.hasData?(v)=>setState((){_seasonRegion=v;_seasonMonthMissing=false;if(v==null)_observationMonth=null;}):null),if(_seasonRegion!=null)...[const SizedBox(height:8),DropdownButtonFormField<int>(key:ValueKey('$_seasonRegion-$_observationMonth'),initialValue:_observationMonth,decoration:InputDecoration(labelText:l.identifyObservationMonth,errorText:_seasonMonthMissing?l.identifyObservationMonthRequired:null),items:List.generate(12,(i)=>DropdownMenuItem(value:i+1,child:Text(_monthName(l,i+1)))),onChanged:(v)=>setState((){_observationMonth=v;_seasonMonthMissing=false;})),if(selected!=null&&selected.note.isNotEmpty)...[const SizedBox(height:6),Text(selected.note,style:Theme.of(context).textTheme.bodySmall)]]]);})])));
  List<Widget> _resultWidgets(AppLocalizations l){if(_results==null)return const[];return[const SizedBox(height:20),Text(l.identifyResults,style:Theme.of(context).textTheme.titleLarge),if(_results!.isEmpty)Padding(padding:const EdgeInsets.all(16),child:Text(l.identifyNoMatches)),..._results!.map((r){final morphology=r.requested==0?l.identifyNoMorphology:'${r.matched}/${r.requested} ${l.identifyTraits}',field=r.fieldRequested==0?'':' · ${r.fieldMatched}/${r.fieldRequested} ${l.identifyField}';return ListTile(title:Text(r.species.commonName),subtitle:Text('${r.species.scientificName} · ${l.identifyMatchScore} ${(r.score*100).round()}% · $morphology$field'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>SpeciesScreen(locale:widget.locale,speciesId:r.species.id))));})];}
  @override Widget build(BuildContext context){final l=AppLocalizations.of(context);return Scaffold(appBar:AppBar(title:Text(l.identifyTitle)),body:SafeArea(child:Column(children:[Expanded(child:FutureBuilder<List<TraitChoice>>(future:_choices,builder:(context,s){if(s.hasError)return Center(child:IconButton(onPressed:_retryChoices,icon:const Icon(Icons.refresh),iconSize:40));if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());final groups=<int,List<TraitChoice>>{};for(final c in s.data??const<TraitChoice>[]){groups.putIfAbsent(c.traitId,()=>[]).add(c);}final list=groups.values.toList(growable:false);return CustomScrollView(slivers:[SliverPadding(padding:const EdgeInsets.fromLTRB(16,16,16,4),sliver:SliverList(delegate:SliverChildListDelegate.fixed([Text(l.identifyIntro),const SizedBox(height:12)]))),SliverPadding(padding:const EdgeInsets.symmetric(horizontal:16),sliver:SliverList(delegate:SliverChildBuilderDelegate((context,i)=>_traitCard(context,l,list[i]),childCount:list.length))),SliverPadding(padding:const EdgeInsets.fromLTRB(16,4,16,16),sliver:SliverList(delegate:SliverChildListDelegate.fixed([_fieldDataCard(l),FilledButton.icon(onPressed:_identify,icon:const Icon(Icons.filter_alt),label:Text(l.identifyShowCandidates)),..._resultWidgets(l)])))]);})) ,const SafetyNotice()])));}
}
extension _FirstOrNull<T> on Iterable<T>{T? get firstOrNull=>isEmpty?null:first;}